language: php

sudo: false

dist: trusty

cache:
    directories:
        - $HOME/.composer/cache

services:
    - redis-server

php:
    - 7.1
    - 7.2
    - 7.3

env:
    - SYMFONY_VERSION=4.3.*@dev

addons:
    apt:
        sources:
            -   sourceline: 'ppa:ondrej/php'
        packages:
            - libsodium-dev

before_install:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then pecl install libsodium; fi
    - pecl info redis
    - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - php -m
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update $COMPOSER_FLAGS

script: ./vendor/bin/phpunit -c . -v

jobs:
    include:
        -   stage: Code Quality
            php: 7.2
            env: CODING_STANDARDS
            script: composer phpcs

        -   stage: Code Quality
            php: 7.2
            env: STATIC_ANALYSIS
            script: composer phpstan

        -   stage: Code Quality
            php: 7.2
            env: BENCHMARK
            script: ./vendor/bin/phpbench run --progress=travis
