language: php

sudo: false

dist: xenial

cache:
  directories:
    - $HOME/.composer/cache

services:
  - redis-server

php:
  - 7.2
  - 7.3

env:
  - SYMFONY_VERSION=3.4.*@dev
  - SYMFONY_VERSION=4.3.*@dev
  - SYMFONY_VERSION=4.4.*@dev

before_install:
  - |
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
    sudo add-apt-repository -y ppa:ondrej/php
    sudo apt update
    sudo apt install -y librabbitmq-dev libsodium-dev

  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then pecl install libsodium; fi
  - pecl info redis
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - php -m
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update $COMPOSER_FLAGS

script: ./vendor/bin/phpunit -c . -v

jobs:
  include:
    - stage: Code Quality
      php: 7.3
      env: CODING_STANDARDS
      script: composer phpcs

    - stage: Code Quality
      php: 7.3
      env: STATIC_ANALYSIS
      script: composer phpstan

    - stage: Code Quality
      php: 7.3
      env: BENCHMARK
      script: ./vendor/bin/phpbench run --progress=travis
