name: PHPStan

on:
  push:

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
        with:
          version: 2
          php_version: 7.4
      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          path: .
          configuration: phpstan.neon.dist
          version: 1.4.3
          php_version: 7.4
          memory_limit: 1G
