Helis\SettingsManagerBundle\Model\SettingModel:
    type: mappedSuperclass
    fields:
        name:
            name: name
            type: string
            length: 128
            nullable: false
            unique: false
        description:
            name: description
            type: string
            length: 255
            nullable: true
            unique: false
        type:
            name: type
            type: setting_type_enum
            nullable: false
        data:
            name: data
            type: json_array
            nullable: false
        choices:
            name: choices
            type: json_array
            nullable: true
            unique: false
    embedded:
        domain:
            class: Helis\SettingsManagerBundle\Model\DomainModel
