Helis\SettingsManagerBundle\Model\TagModel:
    type: mappedSuperclass
    fields:
        name:
            name: name
            type: string
            length: 64
            nullable: false
            unique: true
