Helis\SettingsManagerBundle\Model\DomainModel:
    type: embeddable
    fields:
        name:
            type: string
            length: 128
            nullable: false
            unique: false
        priority:
            type: integer
            nullable: false
            unique: false
            options:
                default: 0
        enabled:
            type: boolean
            nullable: false
        readOnly:
            name: read_only
            type: boolean
            nullable: false
            options:
                default: false
